version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    commit-message:
      prefix: "[dependabot]"
    labels:
      - "automerge"
      - "dependencies"
