version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "11:45"
      timezone: "UTC"
    commit-message:
      prefix: "[dependabot]"
    labels:
      - "automerge"
      - "dependencies"
